### ISSUE TITLE
CNAME 設定似乎錯了

### ISSUE THREAD

**Issue by wildskyf** [noworneverev/marshuang.com#2]
@kidwm 你看得出來是哪裡沒設定好嗎？

**Comment by kidwm** [comment]
哪裡有錯？網站看起來很正常。

**Comment by wildskyf** [comment]
這個 https://marshuang-com.github.io/marshuang.com/ 不會導到 http://marshuang.com/

**Comment by kidwm** [comment]
有哪個站是會導回去的？http://linux-taiwan.github.io/fedora.linux.org.tw/
直接把 repo 改名成 marshuang-com.github.io 就行了啦。

**Comment by wildskyf** [comment]
哦哦，原來是我誤會了。
